### ISSUE TITLE
Is this the new AdminUI ?

### ISSUE THREAD

**Issue by beyondthestatic** [ezsystems/ezplatform-admin-ui#297]
Hello,

what is the difference between this Repo and 'PlatformUIBundle'?

I would love if this is the new approach to get rid of YUI!
Even the Doc ( https://doc.ezplatform.com/en/2.0/guide/extending_ez_platform_ui/ ) already links to this Repo but if i take a look at the roadmap it seems that this AdminUI will be available only for Version 2.0 ?

Would appreciate any Feedback about this subject.

THX in advance, *m

**Comment by andrerom** [comment]
This is the new Admin UI for v2, I'll add some github repository info to make it more clear. Any other kind of info you where missing?

**Comment by beyondthestatic** [comment]
@andrerom , thank you for your quick reply!
after i researched a couple of documents, i found out myself.

looks like platform 2.0 is finally released.
so YUI is gone, good.

we will look into this new UI and updating to 2.0.

**Comment by andrerom** [comment]
> so YUI is gone, good.

In eZ Platform yes, in Studio _(part of eZ Platofmr Enterprise)_ it is still there until tentatively 2.2 where Studio v2 is coming _(similar change as was done here for platform)_.

> we will look into this new UI and updating to 2.0.

great, don't hesitate to ask questions _(here is ok, but main channels are https://discuss.ezplatform.com/ and ezcommunity Slack)_
