### ISSUE TITLE
On empty containers SubItems performs 2 fetch requests

### ISSUE THREAD

**Issue by andrerom** [ezsystems/ezplatform-admin-ui#405]
First one:
```
{ViewInput: {identifier: "subitems-load-location-53", public: false,…}}
  ViewInput: {identifier: "subitems-load-location-53", public: false,…}
    LocationQuery: {Criteria: {}, FacetBuilders: {}, SortClauses: {ContentName: "ascending"},…}
      Criteria: {}
      FacetBuilders: {}
      Filter: {ParentLocationIdCriterion: "53"}
      SortClauses: {ContentName: "ascending"}
      limit: 10
      offset: 0
    identifier: "subitems-load-location-53"
    public: false
```

Second one :
```
{ViewInput: {identifier: "subitems-load-content-info-", public: false,…}}
  ViewInput: {identifier: "subitems-load-content-info-", public: false,…}
    ContentQuery:{Criteria: {}, FacetBuilders: {}, SortClauses: {}, Filter: {ContentIdCriterion: ""}, limit: 0,…}
    identifier: "subitems-load-content-info-"
    public: false
```

Second one has an empty id and limit set to 0, so:
- pro rendering logic fails to take empty containers into account
- dynamic loading logic seems to not take into account a empty location result

**Comment by andrerom** [comment]
@sunpietro I know this is is not the official reporting channel, aware of this one? /cc @lserwatka

**Comment by sunpietro** [comment]
@andrerom yes, I got notification about this issue. It's in my todo list :)

**Comment by sunpietro** [comment]
@andrerom the issue is caused by the assumption that if we don't provide the initial items info from the backend, then the SubItems module should try to fetch it on its own.
It's the feature of the module. Of course, this can be easily changed by removing action that tries to load items when no items were provided with the initial module state.
Is this issue blocking the app or is it worsening app responsiveness?

**Comment by andrerom** [comment]
> Is this issue blocking the app or is it worsening app responsiveness?

It is it worsening app responsiveness, and firing off malformed REST requests.

**Comment by sunpietro** [comment]
Ok then. It's a simple fix.
