### ISSUE TITLE
Wrong use of setup/administrate permission?

### ISSUE THREAD

**Issue by andrerom** [ezsystems/ezplatform-admin-ui#571]
I was trying to debug a client install where they claimed they lost access to administrate users after recent 2.1 to 2.2 upgrade.

These are semi admins, or power editors, so they should have access to:
- administrate users _(and all other content)_

However right now to expose that I need to grant them `setup/administrate` rights, which makes these visible as well as _Users_ under **Admin**:
- _Languages_
- _Content Types_

Which is _not_ wanted.

#### Main issue on _Users_

Possible ways of fixing it:
- Move _Users_ beneath **Content**, so you don't need to grant `setup/administrate`
- Don't require `setup/administrate` to show **Admin**, but instead drop it if user does not have rights to see any sub menu items _(implying we check permissions for all sub items)_

#### Additional issue on _Languages_ and _Content Types_ being shown

Does the following make sense?
- Change Languages menu item to check permission `content/translations` instead of `setup/administrate`
  - This is what `LanguageController` is using, however that might be for something else, as testing on this I seems to have full access to administrate languages just with `setup/administrate`, so there might be several "bugs" here.
- Add missing permission check for Content Types, for 2.2.x use `setup/administrate` but for 2.3:
  - A. Add for instance a `class/view` in order to be able to do it, add BC note that legacy won't respect this and that it's only for platform.
    - Cavat: For cases where users are granted `class/edit` only, they now also need `class/view`
  - B. _[slightly preferred]_ Lets adjust permission api in order to be able to ask if user has rights to _any_ functions on a module, in this case just asking for access to `class` which could for instance return false or array of functions, in this case we can then see if return value evaluates to true before we show menu item.
    -  _SIDE: I can help with this one if accepted, it can be useful in many cases_
    - Cavat: Unless we combine this with A, it will not be possible to grant just `view` rights if someone for some reason have a need for that.

cc @SylvainGuittard @lserwatka

**Comment by SylvainGuittard** [comment]
Hi @andrerom!

We asked the community what approach they prefer to provide access to the sub-menus: https://discuss.ezplatform.com/t/help-us-get-the-permissions-for-the-admin-panel-right/311.
A majority decided to have only one policy to access the admin panel and the sub menus.

I understand the problem with `Users`. `Users` is related to `content/read` and we did not covered this policy on 2.2. We should have this covered on 2.3.

Regarding the issue with `Languages` and `Content Types` could you please confirm that they can see but not edit it. It should be read only.

**Comment by andrerom** [comment]
> confirm that they can see but not edit it. It should be read only.

they can edit languages*, but not content types they can only view there.

* A bit unsure why, can double check

**Comment by SylvainGuittard** [comment]
ping @mikadamczyk who worked on user permissions :)

**Comment by andrerom** [comment]
@lserwatka yeah it was more since it was a open async discussion on how it should behave, and we are all more active on Github then JIRA ;)  You can remove issues tab on this repo once we have summary on JIRA issues to create out of this.

> To manage 'Admin'->'Languages' user must have the policy 'content/translations' same as in kernel. Without this policy, in my installation, 'Languages' and 'Content Types' are in 'read mode'.

Ok, I get why they have this then.

They have _(on purpose)_ `content/*`
However it's not intended they _(power editors)_ should add/remove languages.


@SylvainGuittard So there is a few issues / suggestions for improvements here, however as this can go several directions. Any suggestions? Feel free to ping on slack to discuss ;)

**Comment by barbaragr** [comment]
Moved to jira: https://jira.ez.no/browse/EZP-30141
